
function sleep(n)
    os.execute("sleep " .. tonumber(n))
end

clear_all_shapes()

local s0 = f_shape(function (x)
 return x * x;
end, -4.0, 4.0)
local s1 = f_shape(function (x)
 return x * x * x;
end, -4.0, 4.0)
local s2 = spiral_shape(8,8)
local s3 = circle_shape(5)
local s4 = rectangle_shape(3, 3)
local s5 = triangle_shape(4)
local s6 = pentagon_shape(5)
local s7 = hexagon_shape(6)
local s8 = star_shape(7,8)
local s9 = square_shape(9)
draw(s0)
sleep(7)
convert_shape(s0,s1)
sleep(7)
convert_shape(s1,s2)
sleep(7)
convert_shape(s2,s3)
sleep(7)
convert_shape(s3,s4)
sleep(7)
convert_shape(s4,s5)
sleep(7)
convert_shape(s5,s6)
sleep(7)
convert_shape(s6,s7)
sleep(7)
convert_shape(s7,s8)
sleep(7)
convert_shape(s8,s9)
sleep(7)
convert_shape(s9,s0)
