
function sleep(n)
    os.execute("sleep " .. tonumber(n))
end

clear_all_shapes()
draw(f_shape(function (x)
 return x * x;
end, -4.0, 4.0))
sleep(1)
draw(circle_shape(2))
sleep(1)
draw(rectangle_shape(3, 3))
sleep(1)
draw(triangle_shape(4))
sleep(1)
draw(pentagon_shape(5))
sleep(1)
draw(hexagon_shape(6))
sleep(1)
draw(star_shape(7,8))
sleep(1)
draw(spiral_shape(8,3))
sleep(1)
draw(square_shape(9))
